# Default values for tmp-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: prepor/tmp-app
  tag: master.15
  pullPolicy: IfNotPresent
service:
  name: main
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
hostName: app.team.navimize.com
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

